site_name: Python Invest
repo_url: https://github.com/clcosta/python-invest
repo_name: clcsota/python-invest
nav:
  - User Guide: index.md
  - Advanced: advanced.md
  - Command Line Interface: CLI/cli.md
theme:
  name: material
  favicon: ./images/logo.png
  palette:
  - scheme: default
    primary: deep purple
    toggle:
        icon: material/weather-night
        name: Dark Mode
  - scheme: slate
    primary: deep purple
    toggle:
        icon: material/weather-sunny
        name: Light Mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python-requests.org/en/master/objects.inv
extra_css:
  - ./stylesheets/extra.css

watch:
   - python_invest
